// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WpfApp1.EntityFrameWork;

#nullable disable

namespace WpfApp1.Migrations
{
    [DbContext(typeof(DatabaseContext))]
    [Migration("20240717132129_add-table-task")]
    partial class addtabletask
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.7");

            modelBuilder.Entity("WpfApp1.Models.Task", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("Category")
                        .HasColumnType("INTEGER")
                        .HasColumnName("T_CATEGORY");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("T_DESCRIPTION");

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("TEXT")
                        .HasColumnName("T_END_DATE");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("TEXT")
                        .HasColumnName("T_START_DATE");

                    b.Property<int>("Statues")
                        .HasColumnType("INTEGER")
                        .HasColumnName("T_STATUS");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("T_TITLE");

                    b.HasKey("Id");

                    b.ToTable("TASK");
                });
#pragma warning restore 612, 618
        }
    }
}
